### ISSUE TITLE
Magazyn energii Energa 

### ISSUE THREAD

**Issue by jj641** [thedeemling/hass-energa-my-meter#1]
Dziękuję za super komponent. Działa bezproblemowo po integracji z HA. Długo szukałem takiego rozwiązania.

Czy jest możliwość techniczna wyliczania ilości kW w wirtualnym magazynie energii Energa po rozliczeniu, z datami wprowadzenia, biorąc pod uwagę sumy godzinowych sald dodatnich i ujemnych dla osób rozliczających się na starych zasadach?

**Comment by thedeemling** [comment]
Cieszę się bardzo, że się komuś przydało - trochę się nad nim napracowałem, zwłaszcza przy statystykach :)

Hm, przyznam szczerze, że ja jestem bardzo podstawowym klientem Energi - mam tylko jedno przyłącze PPE i nie produkuję własnej energii, więc musiałbyś mnie nakierować i dać jakieś wskazówki, jak chciałbyś to osiągnąć.

Czy te dane (potrzebne do dokonania obliczeń) są gdzieś w Enerdze (Mój licznik), czy może komponent już je ściąga i chciałbyś je dodatkowo obrobić "po swojemu"?

Chciałbym, żeby komponent `energa_my_meter` robił raczej podstawową operację przenoszenia danych ze strony Mój Licznik do Home Assistanta. Mogę spróbować napisać nowy komponent, który wykorzysta dane płynące z Energi, dokona przeliczeń i doda je do Home Assistanta jako nowe encje (coś w stylu helpera).

Daj znać, spróbujemy coś wymyśleć :)

**Comment by jj641** [comment]
Moje oczy nadal cieszą wykresy, które powstały z użyciem Twojego komponentu w zakładce HA Energia. Wielkie dzięki. Jest to duże ułatwienie podczas analizy zużycia energii elektrycznej. 

Wracając do wirtualnego magazynu energii Energa, w przypadku rozliczenie Net-metering (rozliczenie w systemie upustów) czyli stare zasady, przewodnik po fakturze dla prosumenta jest pod adresem https://www.energa.pl/dom/faktura-prosumencka i interesują nas następujące zmienne:

- suma godzinowych sald dodatnich i suma godzinowych sald ujemnych. Komponent pobiera dane w każdej godzinie doby, więc wyliczenie tych wartości jest chyba możliwe

- kolejne to: Pobranie z magazynu strefa L, Skorygowana suma sald ujemnych strefa L, Saldo bieżące energii strefa L

- i w końcu MAGAZYN ENERGII PO ROZLICZENIU (Razem w magazynie strefa L)

Przykład wyliczania godzinowych sald https://www.brewa.pl/strefa-wiedzy/rozliczanie-prosumenta-w-systemie-net-billingu-w-energa.html

Dyskusja na temat „Wykres zmagazynowanej energii gotowej do odbioru” i przykładowe kody są pod adresem
https://forum.arturhome.pl/t/wykres-zmagazynowanej-energii-gotowej-do-odbioru/5178

W załączeniu przesyłam zdjęcie mojej faktury (rozliczenia co 2 miesiące) dla ilustracji zdefiniowanych przez Energę powyższych zmiennych.
![faktura-salda-magazyn](https://github.com/user-attachments/assets/d6367745-b923-40fd-b54a-33de4e325ee9)

**Comment by thedeemling** [comment]
Wydaje mi się, że dałoby się to osiągnąć przy wykorzystaniu danych produkowanych przez `energa_my_meter` (w postaci godzinnych statystyk w Home Assistant'cie).

Myślę też, że chyba lepiej byłoby to wydzielić do osobnego komponentu, który pozwoliłby na wskazanie, jakich statystyk chcesz używać do przeliczeń (można wskazać np. te stąd - albo, być może, jakieś własne z lokalnych smart liczników) - i on by sobie pobierał dodatkowe dane potrzebne do przeliczeń, a potem pokazywał wyniki. To brzmi jak dodatkowa funkcjonalność nie do końca powiązana (aktualnie?) ze stroną MójLicznik, więc trudno byłoby mi to utrzymywać - przy każdej zmianie kodu staram się wykonać testy, czy niczego nie popsułem, więc zwiększyłby się zdecydowanie impact. Wydzielenie tego do osobnego komponentu uniezależnia obie funkcjonalności i łatwiej je testować/wprowadzać poprawki :)

Nie wiem jednak, czy ja jestem w takim razie odpowiednią osobą do napisania takiego komponentu. Jak będę miał chwilę czasu wolnego, to mogę się nad tym zastanowić, ale pewnie podczas prac deweloperskich przydałby się ktoś, kto ma taki magazyn energii i mógłby potwierdzić działanie alrgorytmu :)

**Comment by jj641** [comment]
Dziękuję za informacje.

Wszystkim prosumentom  otrzymującym faktury z Energii polecam ten komponent do analizy zużycia energii elektrycznej.

**Comment by thedeemling** [comment]
W takim razie - póki co - zamknę tu zgłoszenie. Jeżeli coś się ruszy w temacie, podlinkuję tu nowy komponent :)
