### ISSUE TITLE
Problem z konfiguracją

### ISSUE THREAD

**Issue by JakNo** [thedeemling/hass-energa-my-meter#10]
Cześć,

Mam problem z uruchomieniem integracji. Przy próbie konfiguracji z poziomu GUI po wpisaniu loginu i hasła dostaję komunikat "Błąd połączenia". Wklejam logi:
```
Rejestrator: custom_components.energa_my_meter.energa.connector
Źródło: custom_components/energa_my_meter/energa/connector.py:187
integracja: Mój licznik - Energa Operator (dokumentacja, Problemy)
Pierwsze zdarzenie: 13:52:01 (2 zdarzenia)
Ostatnio zalogowany: 15:28:34

Got an error response from the energa website https://mojlicznik.energa-operator.pl/dp/UserLogin.do: <urlopen error [Errno -5] Name has no usable address>
```

**Comment by thedeemling** [comment]
Cześć.

Wybacz opóźnienie w odpowiedzi - mam aktualnie mało czasu wolnego, za co przepraszam ;)

`<urlopen error [Errno -5] Name has no usable address>` jest dosyć nietypowym błędem i widzę podobne wystąpienia w innych wątkach związanych z home assistantem (jak https://github.com/home-assistant/core/issues/94418). Będe potrzebował więcej informacji.

Czy mógłbys włączyć logi w trybie debug dla `energa_my_meter` i podesłać je (usuwając swoje dane prywatne jak nr licznika/przyłącza/adres itd)?

**Comment by JakNo** [comment]
Nie ma problemu, dzięki za odpowiedź :)

1. Korzystam z OS-a zainstalowanego na Raspberry Pi 4. Wczoraj zaktualizowałem do najnowszej wersji, ale niestety nie pomogło to rozwiązać problemu.
2. Podpowiedziałbyś jak tego dokonować? Próbowałem ustawić logi debugowania już wczoraj dodając linijkę `custom_components.energa_my_meter: debug` do configuration.yaml, ale w logach nie widzę nic innego ponad to, co podesłałem w poście.
3. Tak, dokładnie. Po zalogowaniu się w przeglądarce do MojegoLicznika mam dostęp do danych o zużyciu.

**Comment by JakNo** [comment]
@thedeemling Ok, wydaje mi się, że udało mi się odnaleźć dodatkowe logi, ale nie wiem, na ile okażą się przydatne :)

```
2024-12-12 17:00:00.005 DEBUG (SyncWorker_4) [custom_components.energa_my_meter.energa.client] Opening a new connection to the Energa website...
2024-12-12 17:00:00.065 ERROR (SyncWorker_4) [custom_components.energa_my_meter.energa.connector] Got an error response from the energa website https://mojlicznik.energa-operator.pl/dp/UserLogin.do: <urlopen error [Errno -5] Name has no usable address>
```

**Comment by JakNo** [comment]
@thedeemling problem rozwiązał się po ostatniej aktualizacji Home Assistanta - jestem już w stanie skonfigurować dodatek :)

**Comment by thedeemling** [comment]
Cieszy mnie, że zadziałało :)

Może warto, żebym dodał jakąś notkę do README do known issues na ten temat?

**Comment by JakNo** [comment]
Jasne. Myślę, że to dobry pomysł :)
