### ISSUE TITLE
współczynnik do Net-Metering

### ISSUE THREAD

**Issue by cHunter789** [thedeemling/hass-energa-my-meter#4]
Czy jest opcja dodać zmienną ustawiającą współczynnik kosztu oddania energii dla sieci? Byłoby to nieocenione dla szczęśliwców podpiętych pod Net-metering. Chodzi o to by był parametr pozwalający zdefiniować współczynnik do mnożenia godzinnych zestawień np. 0,8*{energy_produced}. Wtedy użytkownicy z Net-meteringiem widzieliby ile faktycznie maja energii odłożonej w magazynie. Teraz trzeba robić osobne karty z kombinować z templete sensor.

**Comment by cHunter789** [comment]
OK widze że temat jest juz ujęty szerzej z zamkniętych requestach. Moja propozycja nie była tak kompleksowa.

**Comment by thedeemling** [comment]
Czy chodzi o temat związany z https://github.com/thedeemling/hass-energa-my-meter/issues/1 ?

Jestem otwarty na propozycje i ulepszenia komponentu (wygoda i zadowolenia użytkowników przede wszystkim ;) ), jednak chciałbym się ograniczyć w tym komponencie do pobierania danych ze strony "mój licznik". Jeżeli te informacje się tam znajdują, a ja ich jeszcze nie pobieram, daj znać - dodam wsparcie (przy Twojej pomocy).

Jeżeli chodzi Ci o dane związane ze zgłoszeniem powyżej, to chyba najlepiej byłoby zrobić nowy komponent, który skorzysta z danych tego tutaj i dokona przeliczeń.
