### ISSUE TITLE
Wartości w encjach nie odpowiadają nazwom encji

### ISSUE THREAD

**Issue by tomekszy** [thedeemling/hass-energa-my-meter#9]
![zrzut2](https://github.com/user-attachments/assets/0003b288-be17-40ce-a9fc-6c5b2bc11503)
Jak widać sam odczyt danych jest ok, tylko dane "nie trafiają" do odpowiednich encji - Energy produced powinno być Energy consumed (Strefa 2), a Meter reading - Energy consumed (Strefa 1). Normalnie zmieniłbym wyświetlane nazwy, ale niestety ma to znaczenie podczas pomiaru zuzytej energii, ponieważ encje energy consumed są typu `total_energy_consumption`, a takich właśnie potrzebuję do obliczenia łącznego zużycia.

**Comment by thedeemling** [comment]
Cześć. Wybacz małe opóźnienie w reakcji, ale aktualnie mam trochę mniej czasu wolnego.

Wydaje mi się, że muszę lepiej zrozumieć Twoje potrzeby.
Zapoznawałeś się może z dokumentacją? https://github.com/thedeemling/hass-energa-my-meter?tab=readme-ov-file#statistics-sensors - tam opisuję różnicę między encjami statystycznymi (zawierającymi dane historyczne) a rzeczywistymi (najnowszy odczyt licznika).

O ile rozumiem, chodzi Ci o to, że tamte dwie encje mają status `Nieznany`, a chciałbyś użyć stref na wykresie dashboardu Energii.
W takim razie powinieneś użyć właśnie tych dwóch encji ze stanem `nieznany` - one będą działać na dashboardzie.

W przypadku `Meter reading` i `Energy produced` - to encje zawierające ostatni odczyt licznika na stronie Energii. Zgadzam się, że nazewnictwo jest słabe, z checią je zmienię. Podobny temat został poruszony w https://github.com/thedeemling/hass-energa-my-meter/issues/7. 

Jeżeli masz jakieś propozycje do nazw tych encji, zaproponuj  je tutaj/tam, postaram się przy okazji poprawić (o ile nie spowodują problemów użytkownikom).

**Comment by JakNo** [comment]
@thedeemling wydaje mi się, że autor miał na myśli błędnie przypisane pola _Energy produced_ i _Meter reading_. U mnie jest podobny case:

<img width="472" alt="obraz" src="https://github.com/user-attachments/assets/ab2cbc4a-d102-492e-8c7a-491dfe470c0c" />


podczas gdy na mojlicznik mam takie dane:

<img width="472" alt="obraz" src="https://github.com/user-attachments/assets/5a868f09-256b-4eb1-9edb-7e632346246a" />

Zatem Energy produced powinna nazywać się np. Energy consumed (Strefa 2), bo "Energy produced" sugeruje produkcję energii przez PV, a takowych nie posiadam :)

**Comment by tomekszy** [comment]
dokładnie o to mi chodziło :) Nie produkuję energii, natomiast mam umowę G12W (2 taryfy), i to, co faktycznie jest odczytem licznika z pierwszej taryfy, trafia do encji Meter Reading, natomiast druga taryfa trafia do Energy produced - a powinno trafiać odpowiednio do Energy consumed - Strefa 1 i Strefa 2

**Comment by thedeemling** [comment]
W screenshocie załączonym z https://forum.arturhome.pl/t/energa-moj-licznik-custom-component/13239/20?u=the_deemed  widzę, ze energia produkowana też się tu wyświetla na jednym ekranie.

Byłbym ekstra wdzięczny za potwierdzenie, że te pozostałe też są opakowane w taki HTML:
![image](https://github.com/user-attachments/assets/34ea366d-e211-4329-9ff6-bbddd470bd66)

Dajcie znać, czy wolicie nazwy encji w stylu:
- Meter reading - A+ strefa 1
- Meter reading - A- strefa 2
itd.

Czy też może raczej
- Meter reading - energy consumed (strefa 1)
- Meter reading - energy produced (strefa 2)
itd.

**Comment by JakNo** [comment]
co do energii produkowanej to niestety się nie wypowiem, ale wydaje mi się, że powinny mieć ten sam format w HTML-u. U mnie wygląda to tak:

<img width="874" alt="obraz" src="https://github.com/user-attachments/assets/6c9147a1-9e2b-4a7c-bfe8-811c657c0ac8" />

Jeśli chodzi o nazewnictwo to dla mnie wystarczająca byłaby pierwsza opcja, czyli np. _Meter reading - A+ strefa 1_, bo byłoby zbieżne z tym, co jest w UI mojlicznik. Chyba, że możnaby dać użytkownikowi wybór na etapie setupu dodatku, ale nie wiem na ile jest to wykonalne :)

**Comment by thedeemling** [comment]
No dobra, w takim razie w okresie międzyświątecznym przygotuję poprawkę, żebyście od Nowego Roku mogli zbierać prawidłowe dane historyczne :)

**Comment by tomekszy** [comment]
Dzięki! Miło słyszeć, że działasz tak szybko :)

**Comment by thedeemling** [comment]
W ramach https://gitlab.com/home-assistant-custom-components/hass-energa-my-meter/-/merge_requests/19/commits wprowadziłem poprawkę, która powinna rozwiązać Wasze problemy.

Aktualnie leży ona w branchu https://github.com/thedeemling/hass-energa-my-meter/tree/feature/support_all_meter_readings - jeżeli chcecie, prosiłbym o przetestowanie, czy działa prawidłowo :)

Za jakiś czas (jak nie znajdę błędów), wrzucę ją do głównej gałęzi kodu i wypuszczę nową wersję.

**Comment by tomekszy** [comment]
Mam zainstalowany dodatek za pomocą HACSa, w jaki sposób mogę przełączyć się na inny branch? gdzie można tam wpisać git chckout nazwa_brancha ;)

**Comment by JakNo** [comment]
> Mam zainstalowany dodatek za pomocą HACSa, w jaki sposób mogę przełączyć się na inny branch? gdzie można tam wpisać git chckout nazwa_brancha ;)

Myślę, że trzeba ręcznie wrzucić folder z dodatkiem z nowego brancha do custom_components w Home Assistancie

**Comment by tomekszy** [comment]
Jeżeli chodzi o strefę dzienną i nocną, to teraz te strefy są w dobrych miejscach
![image](https://github.com/user-attachments/assets/0b02d40f-6090-4554-8ae6-514712e95287)
Natomiast mam pytanie co do pozostałych encji - Energy consumed występują 2 razy dla strefy dziennej i 2 razy dla nocnej, dodatkowo są niedostępne. Domyślam się, że ma to związek z zakładką energia, gdzie można sobie dodać faktyczny pobór mocy z sieci. I tu mam 2 pytania - 
1. Co zrobić, żeby encje te były dostępne?
2. Do czego służy jedna i druga encja i czemu są dwie?
3. Jak dołączyć realne zużycie do karty Energia ALE w taki sposób, żeby encja z dodatku nie dodawała zużycia rzeczywistego jako kolejnego zużycia, ale żeby pokazywała zużycie z innych odbiorników jako część zużycia całkowitego? Dla przykładu - moja karta Energia wygląda tak:
![image](https://github.com/user-attachments/assets/6e59bc47-fd84-4785-8b6d-c8548d912166)
I teraz chciałbym dodać encję z rzeczywistym poborem energii z dodatku (zakładam, że po uporaniu się z tym, że te encje są póki co niedostępne):
![image](https://github.com/user-attachments/assets/bc97c099-e6ed-40e2-b470-bae4e8c60034)
ale jak dodać to w taki sposób, żeby pozostałe zużycie, takie jak mam tam skonfigurowane (np bojler, grzejniki, podłogówki) stało się częścią zużytej energii z licznika, a nie się do niej dodały - krótko mówiąc dalej chcę śledzić jednostkowe zużycie energii z poszczególnych urządzeń, ale jednocześnie widzieć pełne zużycie na podstawie licznika.

**Comment by thedeemling** [comment]
O, czyli działa, jak trzeba w kwestii liczników? 

1 i 2.. Zignoruj niedostępność encji `Energy ...`. One działają :) wynikają z ograniczenia home assistanta, którego nie umiem obejść. `Meter reading` zawierają najnowsze wartości na liczniku, ale Energa rzadko ja aktualizuje, więc nie mają godzinnego zużycia. Wartości zużycia co godzinę pobieram z Energii z innego miejsca, ale HASS nie pozwala "nadpisać" starych wartości dla czegoś, co ma stan (jest dostępne i ma wartość). Dlatego też zrobiłem nowe encje, które mają dane historyczne, ale bez aktualnej wartości. 

Te encje Meter reading służą do pokazania najnowszego stanu licznika. Encje typu Energy... uzywane są na dashboardzie od energii

3. Użyj encji typu Energy jako ŹRÓDŁA. dodaj wszystkie, jakie stworzył mój dodatek. Zużycie energii typu Smart gniazdka dodaj jako URZĄDZENIA. Reszta zajmie się HASS :)

**Comment by thedeemling** [comment]
Daj znać, czy to rozwiązuje problem :) Zgłoszenie zamknę po wypuszczeniu nowej wersji

**Comment by tomekszy** [comment]
Tak, działa wszystko jak trzeba, po skorzystaniu z Twoich rad mam osobno urządzenia i osobno rzeczywiste zużycie z sieci (tzn póki co jeszcze nie mam, ale jak zostaną pobrane przyrosty to zakładam, że się pojawi ta informacja), encje "podwójne", o których pisałem też już się wyjaśniły - po prostu trzeba było usunąć je z rejestru encji, bo były to pozostałości po poprzedniej wersji dodatku. Także na razie chyba wszystko ok na tą chwilę, ale dam jeszcze znać, czy zaktualizuje się zużycie (czyli pewnie jutro)

**Comment by thedeemling** [comment]
U mnie też Energa od dwóch dni nie raportuje przyrostów :( Ale dla kilku dni wstecz powinieneś już widzieć wykresiki (o ile skonfigurowałeś sobie dodatek, zeby pobierał dane historyczne sprzed X dni :) ).

Trzymam kciuki, żeby działało! :)

**Comment by thedeemling** [comment]
Wypuściłem poprawkę w https://github.com/thedeemling/hass-energa-my-meter/releases/tag/2.3.0
